### ISSUE TITLE
No Proofs Available Error... or Misunderstanding?

### ISSUE THREAD

**Issue by technohippies** [w3s-project/w3up#1355]
I am successfully uploading data to w3 in my SolidJS dapp and I get an IPFS CID upon success. However, in the w3 CLI, when I run w3 usage report, I get this error for every file I uploaded through my dapp:

account: did:mailto:__arstone.com:997fallon * space: did:key: z6MkjM...Nf error: no proofs available for resource did:key: z6MkjM...Nf and ability usage/report

In addition, none of the files appear on the web3.storage website. Perhaps my understanding of did:key's is poor, but any help would be deeply appreciated.

Here's my SolidJS Typescript component:
https://pastebin.com/39WKksBT

Here are the logs from a successful upload:
https://pastebin.com/q5XiW9xe

🙏 danke | TY | merci

**Comment by alanshaw** [comment]
@technohippies did you create the space with w3 CLI or get access delegated to it?

If you were delegated access and want to use the `usage/report` capability you need to obtain a new delegation and include that capability it in the list of capabilities for the delegation.

**Comment by technohippies** [comment]
@alanshaw users create their own space using the w3up-client in the dapp. I followed the documentation but proofs seem to take ~3 days to appear? Not clear. The CIDs work, so maybe proofs are being processed, Filecoin?

**Comment by Mihir02** [comment]
@technohippies can you help me with uploading files on web3.storage ipfs, I'm facing errors as I wanted to load a pre-existing space and upload data on that space...

**Comment by alanshaw** [comment]
Filecoin proofs are different proofs to the proofs you mention in the error message.

It sounds like you have successfully uploaded files and they are now available on Filecoin. Due to the aggregation process it can take a few days for inclusion and aggregation proofs to become available.

**Comment by alanshaw** [comment]
> @technohippies can you help me with uploading files on web3.storage ipfs, I'm facing errors as I wanted to load a pre-existing space and upload data on that space...

Can you open a new issue and include your error message and a code sample? Then we can help.
