### ISSUE TITLE
Wire index/add handler to write index that freeway reads from

### ISSUE THREAD

**Issue by Gozala** [w3s-project/w3up#1404]
## Context

[Freeway](https://github.com/web3-storage/freeway) utilizes set of R2 buckets to provide read interface

- `CARPARK` - CAR file storage area. Key format `<CAR_CID>/<CAR_CID>.car`
- `SATNAV` - Indexes of block offsets within CARs. Key format `<CAR_CID>/<CAR_CID>.car.idx`, index format [MultihashIndexSorted](https://ipld.io/specs/transport/car/carv2/#format-0x0401-multihashindexsorted).
- `DUDEWHERE` - Mapping of root data CIDs to CAR shard CID(s). Key format `<DATA_CID>/<CAR_CID>`.

How it works:

1. Extract `DATA_CID` from URL.
1. Lookup `CAR_CID`(s) in `DUDEWHERE`.
1. Read indexes from `SATNAV`
1. UnixFS export directly from `CARPARK` using index data to locate block positions.

## What

- #1402 
- #1403 

## Why

Otherwise uploads content uploaded through blob/add will be readable via Freeway

## Deliverable

When this is closed content added via `blob/add` and then indexed via `index/add` should be readable via w3s.link gateway.

**Comment by alanshaw** [comment]
Note: we decided to not do this, and freeway uses materialized location claims instead.
