### ISSUE TITLE
Wire index/add handler to write derived hoverboard block level index

### ISSUE THREAD

**Issue by Gozala** [w3s-project/w3up#1405]
## Context

[Hoverboard](https://github.com/web3-storage/hoverboard/) facilitates reads over bitswap. It receives request for the block and looks up index in the dynamo `prod-ep-v1-blocks-cars-position` table which maps block multihash to CAR (bucket) paths. From the car path it derives CAR multihash and attempts to reads from preconfigured R2 and S3 buckets.

## What

- Derive block level index records from [dag index](https://github.com/w3s-project/specs/blob/main/w3-index.md#sharded-dag-index-example), passed into #1401, and write them into dynamo table.
- ❗️Note that we should also create a record that spans the whole blob range even if it is not manually described in shards

## Why

Otherwise content uploaded through blob/add will not be readable via bitswap

## Deliverable

Reading blocks uploaded through `blob/add` and published via `index/add` should be readable via bitswap from web3.storage peer.

**Comment by Gozala** [comment]
> ❗️Note that we should also create a record that spans the whole blob range even if it is not manually described in shards

I am just realizing that this may not be possible per current spec because size of the blob itself is not captured, we probably should amend spec to fix that

**Comment by alanshaw** [comment]
resolved in https://github.com/w3s-project/w3infra/pull/363
