### ISSUE TITLE
Wire index/add handler with IPNI publisher-lambda

### ISSUE THREAD

**Issue by Gozala** [w3s-project/w3up#1406]
## Context

System uses [publisher-lambda](https://github.com/elastic-ipfs/publisher-lambda/tree/main) that receives block multihashes on "Multihashes SQS topic" from which it creates and publishes IPNI advertisements. This makes blocks served by [hoverboard](https://github.com/web3-storage/hoverboard) - w3up bitswap peer discoverable on the network.

## What

Put all the multihashes in the [dag index](https://github.com/w3s-project/specs/blob/main/w3-index.md#sharded-dag-index-example) (passed into https://github.com/w3s-project/w3up/issues/1401) into multihashes queue that publisher lambda reads from.

## Why

Without this network will not be able to discover that our bitswap peer serves blocks stored via `blob/add` and published `index/add` capabalities.

## Delivered

1. When done one should be able to query IPNI and discover that blocks added through `blob/add + index/add` are provided by w3up bitswap peer.
2. Once #1405 is also done one should be able to access content added through `blob/add + index/add` via kubo node without manually connecting it to w3up bitswap peer.

**Comment by alanshaw** [comment]
resolved in https://github.com/w3s-project/w3infra/pull/363
