### ISSUE TITLE
Assert equivalence claims for submitted filecoin pieces

### ISSUE THREAD

**Issue by Gozala** [w3s-project/w3up#1407]
## Context

Currently system seems to [issue equivalence claims](https://github.com/w3s-project/w3up/blob/2e3ef6180fde897c5f5b583408e443909c0c91ba/packages/filecoin-api/src/storefront/events.js#L123-L129) after piece is submitted, which ensures that when SPs access piece via roundabout they will be redirected to the location from which they can read corresponding car.

## What

With blob API we no longer using CARs and will change equivalence claims to extends support for blobs https://github.com/w3s-project/content-claims/issues/60

We need to ensure that issued equivalence claims is aligned with ☝️

**Comment by Gozala** [comment]
@vasco-santos I think you could help fill this out with more details as I'm getting bit lost

**Comment by alanshaw** [comment]
I believe the equivalence claim is now issued by the pipeline as a "raw" codec CID. @vasco-santos please correct me if wrong!
