### ISSUE TITLE
Add support for submitting blobs to a filecoin pipeline

### ISSUE THREAD

**Issue by Gozala** [w3s-project/w3up#1408]
## Context

At the moment most of the filecoin pipeline assumes that all `content` links are CARs, which may not be the case with Blobs. We need to ensure that blobs can go through filecoin pipeline.

  - https://github.com/w3s-project/content-claims/issues/60
  - https://github.com/w3s-project/w3up/issues/1407
  - https://github.com/w3s-project/w3infra/issues/357

## What

Submit blobs to the filecoin pipeline

## Why

So that content added as blobs can lands on filecoin

**Comment by Gozala** [comment]
@vasco-santos I think it would make most sense to just extend support to `raw` cids (as opposed to adding multihash support) mostly because I expect it to be less work and it makes sense as we address content either as a car or as a raw blob. I am also more convinced that equivalence claims should use cids as opposed to cid and multihash.

**Comment by vasco-santos** [comment]
1. We need client to side `raw` CID instead of `carCID` with `filecoin/offer`
2. (we agreed we can do this as follow up) Equivalency claim issued by filecoin pipeline can pick the digest of the received `raw` CID

**Comment by vasco-santos** [comment]
Closing by merging https://github.com/w3s-project/w3up/pull/1450#pullrequestreview-2055160233
